version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker_data/pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -h localhost -d ${DB_NAME} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
