version: "3.9"
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - ./docker_data/pg_data:/var/lib/postgresql/data

